using System;

namespace SqlLinqer.Modeling
{
    /// <summary>
    /// Defines a field/property as the primary key
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
    public sealed class SqlPrimaryKey : Attribute
    {
        /// <summary>
        /// Primary key is generated by the database
        /// </summary>
        public readonly bool DbGenerated;

        /// <summary>
        /// Defines a field/property as the primary key
        /// </summary>
        public SqlPrimaryKey()
        {
            DbGenerated = true;
        }

        /// <summary>
        /// Defines a field/property as the primary key
        /// </summary>
        /// <param name="dbGenerated">If the database generates the primary key</param>
        public SqlPrimaryKey(bool dbGenerated)
        {
            DbGenerated = dbGenerated;
        }
    }
}
