using System.Reflection;

namespace SqlLinqer.Relationships
{
    /// <inheritdoc/>
    public class SQLPrimaryKeyMemberInfo : SQLMemberInfo
    {
        /// <summary>
        /// Indicates the primary key id generated by the database
        /// </summary>
        public bool DBGenerated { get; private set; }

        /// <inheritdoc/>
        public SQLPrimaryKeyMemberInfo(SQLConfig config, MemberInfo info, string name = null, bool dbGenerated = false)
            : base(config, info, name)
        {
            DBGenerated = dbGenerated;
        }
    }
}
